### ISSUE TITLE
Addon fails to initialize

### ISSUE THREAD

**Issue by mkroman** [Yoshiofthewire/CrunchyXBMC#25]
Hi,

When trying to open the addon, it fails. It started happening recently. Every once in a while, it works, but not always, I haven't managed to figure out why it sometimes works.

I'm running Crunchyroll 2.1.2 on OpenELEC 5.0.8.

Here's the error message:

```
14:12:17 T:1616499776  NOTICE: -->Python Interpreter Initialized<--
14:12:17 T:1616499776  NOTICE: [PLUGIN] 'Crunchyroll: version 2.1.2' initialized!
14:12:17 T:1616499776  NOTICE: CR: Valid auth token was detected. Restarting session.
14:12:17 T:1616499776  NOTICE: CR: makeAPIRequest: get JSON
14:12:17 T:1616499776  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/start_session.0.json
14:12:17 T:1616499776  NOTICE: CR: makeAPIRequest: options = access_token=xxxxxxxxx&version=2313.8&device_type=com.crunchyroll.iphone&locale=enUS&auth=xxxxxxxxxxxxxx
14:12:19 T:1616499776  NOTICE: CR: Session restart successful. Session ID: xxxxxxxxxxxxxxxxx
14:12:19 T:1616499776  NOTICE: CR: Attempting to report usage
14:12:20 T:1616499776  NOTICE: CR: User is a premium anime|drama|manga member
14:12:20 T:1616499776   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'cPickle.UnpicklingError'>
                                            Error Contents: pickle data was truncated
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.crunchyroll-takeout/default.py", line 38, in <module>
                                                crunchy_main.main()
                                              File "/storage/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 356, in main
                                                check_mode(args)
                                              File "/storage/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 313, in check_mode
                                                log("CR: Main: args = %s" % str(args.__dict__), xbmc.LOGDEBUG)
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/UserDict.py", line 172, in __repr__
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/UserDict.py", line 111, in iteritems
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/shelve.py", line 122, in __getitem__
                                            UnpicklingError: pickle data was truncated
                                            -->End of Python script error report<--
14:12:20 T:1969901568   ERROR: GetDirectory - Error getting plugin://plugin.video.crunchyroll-takeout/
14:12:20 T:1969901568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll-takeout/) failed
```

**Comment by Yoshiofthewire** [comment]
This is failing to open the storage file.
2.2 should work around this.
