### ISSUE TITLE
Updated: Former Queue list impossible to access NOW can't use plugin

### ISSUE THREAD

**Issue by tamodolo** [Yoshiofthewire/CrunchyXBMC#31]
Kodi just throw this on the log file:

38 T:9724  NOTICE: [PLUGIN] 'Crunchyroll: version 2.2' initialized!
16:44:38 T:9724  NOTICE: CR: Queue: queue type is 0
16:44:38 T:9724  NOTICE: CR: makeAPIRequest: get JSON
16:44:38 T:9724  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/queue.0.json
16:44:38 T:9724  NOTICE: CR: makeAPIRequest: options = locale=enUS&media_types=anime%7Cdrama&version=2313.8&session_id=olojvswmzgg16qdiegvzafawddjh1huv&fields=media.episode_number%2Cmedia.name%2Cmedia.description%2Cmedia.media_type%2Cmedia.series_name%2Cmedia.available%2Cmedia.available_time%2Cmedia.free_available%2Cmedia.free_available_time%2Cmedia.duration%2Cmedia.playhead%2Cmedia.url%2Cmedia.screenshot_image%2Cimage.fwide_url%2Cimage.fwidestar_url%2Cseries.landscape_image%2Cseries.series_id%2Cimage.full_url
16:44:40 T:9724  NOTICE: CR: Queue: request['error'] = False
16:44:40 T:9724  NOTICE: CR: Queue: has 72 series
16:44:40 T:9724   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('most_likely_media',)
                                            Traceback (most recent call last):
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\default.py", line 38, in <module>
                                                crunchy_main.main()
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\crunchy_main.py", line 360, in main
                                                check_mode(args)
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\crunchy_main.py", line 335, in check_mode
                                                crj.queue(args)
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\crunchy_json.py", line 857, in queue
                                                'fanart')
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\crunchy_json.py", line 654, in list_media_items
                                                if mode == "queue"
                                            KeyError: ('most_likely_media',)
                                            -->End of Python script error report<--
16:44:40 T:6464   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.crunchyroll-takeout/?complete=True&count=0&duration=0&fanart=C%3a%5cUsers%5cOtavio%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.crunchyroll-takeout-github%5cfanart.jpg&filterx=None&icon=None&id=None&media_type=None&mode=queue&name=Minha%20Fila&offset=0&playhead=0&plot=None%2520&season=1&series_id=None&url=None&year=0
16:44:40 T:6464   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll-takeout/?complete=True&count=0&duration=0&fanart=C%3a%5cUsers%5cOtavio%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.crunchyroll-takeout-github%5cfanart.jpg&filterx=None&icon=None&id=None&media_type=None&mode=queue&name=Minha%20Fila&offset=0&playhead=0&plot=None%2520&season=1&series_id=None&url=None&year=0) failed

Thanks!

UPDATE

Here is the log for the problem today:

20:36:36 T:7148  NOTICE: -->Python Interpreter Initialized<--
20:36:36 T:7148  NOTICE: [PLUGIN] 'Crunchyroll: version 2.2' initialized!
20:36:37 T:7148  NOTICE: CR: Valid auth token was detected. Restarting session.
20:36:37 T:7148  NOTICE: CR: makeAPIRequest: get JSON
20:36:37 T:7148  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/start_session.0.json
20:36:37 T:7148  NOTICE: CR: makeAPIRequest: options = access_token=QWjz212GspMHH9h&version=2313.8&device_type=com.crunchyroll.iphone&locale=enUS&auth=LdZhdf1JoYRlTHrKLv1A36II2S4flKmHwSapOZ7Knk2atIIRgQhY%2F%2FL%2FzaF7rFVhrQgySR5PmElvl1PGAuhM8tjEsdSeSSE7fESfxZneG%2BnAm8VqXWDQLwMxJLoNEuMidZxrzLNz3CMO%2BeX47OC9hA%3D%3D%3ACMW5VKDoZjCrzlFtNTrYFA%3D%3D&device_id=FFFF7xEl-KODI-hxF7-cAix-8fKzXD2IljWu
20:36:38 T:7148   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'read'
                                            Traceback (most recent call last):
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\default.py", line 38, in <module>
                                                crunchy_main.main()
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\crunchy_main.py", line 352, in main
                                                if crj.load_pickle(args) is False:
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\crunchy_json.py", line 188, in load_pickle
                                                current_datetime):
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\crunchy_json.py", line 316, in _restart_session
                                                args.user_data['auth_expires']    = dateutil.parser.parse(request['data']['expires'])
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\dateutil\parser.py", line 697, in parse
                                                return DEFAULTPARSER.parse(timestr, **kwargs)
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\dateutil\parser.py", line 301, in parse
                                                res = self._parse(timestr, **kwargs)
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\dateutil\parser.py", line 349, in _parse
                                                l = _timelex.split(timestr)
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\dateutil\parser.py", line 143, in split
                                                return list(cls(s))
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\dateutil\parser.py", line 137, in next
                                                token = self.get_token()
                                              File "C:\Users\Otavio\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout-github\resources\lib\dateutil\parser.py", line 68, in get_token
                                                nextchar = self.instream.read(1)
                                            AttributeError: 'NoneType' object has no attribute 'read'
                                            -->End of Python script error report<--
20:36:38 T:3100   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.crunchyroll-takeout/
20:36:38 T:3100   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll-takeout/) failed

The plugin is crashing when atempt to use it. Please let me know if you need some more info. Thank you for the great work!

**Comment by Yoshiofthewire** [comment]
When did you get the error?
What shows are in your Queue?

**Comment by tamodolo** [comment]
I get the error just now to get the log for the issue but I'm having it a few days by now.

the shows on the quere are (in this order)

-one piece
-kyoukai no Rinne
-ore monogatari
-shokugeki no soma
-durarara!!
-gate
-classrom crisis
-charlotte
-rokka no yuusha
-ushio to tora
-gakkou gurashi
-danchigai
-okusama ga sentokaichou!
-himouto! umaru-chan
-gatchaman crowds
-naruto shippuden
-god eater
-saint seyia omega
-wizard barrister
-hajime no ippo ~rising~
-wonder momo
-wake up, girls! (this one is odd... the queue in the site don't know what is the next episode)
-fate/kaleid liner prism illya
-hayate no gotoku!
-hayate no gotoku! (I don't know why crunchyroll separated this anime in two itens)
-ore no nounai sentakushi ga, gakuen love comedy wo...
-papa no Iukoto wo kikinasai!
-yuruYuri
-yusha ni narenakatta ore shibushibu shushoku wo.....
-shinryaku! ika musume
-shirokuma cafe
-blade & souls
-soredemo sekai wa utsukushii
-mahouka koukou no rettousei
-makin bone
-kamigami no asobi
-kirino no chord -blue sky-
-captain earth
-kindaichi shounen no jikenbo R
-mekaku city actors
-gochuumon wa usagi desu ka?
-fuuun ishin dai shogun
-hitsugi no chaika
-kanojo ga flag wo oraretara
-zero no tsukaima
-inugami-san to nekoyama-san
-love live!
-bungaku shoujo (seems broken as wake up, girls!)
-strait jacket (seems broken too)
-glassip
-shirogane no ishi argebollen
-bakumatsu rock
-futsuu no joshikousei ga [locodol] yattemita
-dramatical murder
-hanayamata
-yuuki yuuna wa yuusha de aru
-momo kyun sword
-love stage!!
-ai-mai-mi ~ mousou catastrophe ~
-kuroshitsuji: book of circus
-seirei tsukai no blade dance
-rokujouma no shinryakusha?!
-nobunaga concerto
-magimoji rurumo
-sabagebu!
-himegoto
-toradora!
-seto no hanayome
-anime de wakaru shinryounaika
-orenchi no furo jijou
-shinmai maou no keiyakusha
-denki-gai no honya-san
-saint seyia soul of gold
-inferno cop
-tsukimonogatari
-nekomonogatari (kuro)
-jojo no kimyou na bouken
-tesagure! bukatsumono

**Comment by tamodolo** [comment]
Just updated the issue to reflect current state.

**Comment by evaryont** [comment]
I'm also getting an error when trying to acess the queue, but it's a different error. Though, it is consistent for me, even after clearing out addon data and the addon itself (as fresh a crunchyroll plugin as I could I think of):

```
22:19:53 T:6388  NOTICE: [PLUGIN] 'Crunchyroll: version 2.2.0' initialized!
22:19:53 T:6388  NOTICE: CR: makeAPIRequest: get JSON
22:19:53 T:6388  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/queue.0.json
22:19:53 T:6388  NOTICE: CR: makeAPIRequest: options = locale=enUS&media_types=anime%7Cdrama&version=2313.8&session_id=(snip)&fields=media.episode_number%2Cmedia.name%2Cmedia.description%2Cmedia.media_type%2Cmedia.series_name%2Cmedia.available%2Cmedia.available_time%2Cmedia.free_available%2Cmedia.free_available_time%2Cmedia.duration%2Cmedia.url%2Cmedia.screenshot_image%2Cimage.fwide_url%2Cimage.fwidestar_url%2Cseries.landscape_image%2Cimage.full_url
22:19:54 T:6388  NOTICE: CR: A valid session was detected. Using existing session ID: (snip)
22:19:54 T:6388  NOTICE: CR: User is a premium anime|drama|manga member
22:19:54 T:6388  NOTICE: CR: Queue: queue type is 0
22:19:54 T:6388  NOTICE: CR: makeAPIRequest: get JSON
22:19:54 T:6388  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/queue.0.json
22:19:54 T:6388  NOTICE: CR: makeAPIRequest: options = locale=enUS&media_types=anime%7Cdrama&version=2313.8&session_id=(snip)&fields=media.episode_number%2Cmedia.name%2Cmedia.description%2Cmedia.media_type%2Cmedia.series_name%2Cmedia.available%2Cmedia.available_time%2Cmedia.free_available%2Cmedia.free_available_time%2Cmedia.duration%2Cmedia.playhead%2Cmedia.url%2Cmedia.screenshot_image%2Cimage.fwide_url%2Cimage.fwidestar_url%2Cseries.landscape_image%2Cseries.series_id%2Cimage.full_url
22:19:55 T:6388  NOTICE: CR: Queue: request['error'] = False
22:19:55 T:6388  NOTICE: CR: Queue: has 28 series
22:19:55 T:6388   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\colin\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\default.py", line 38, in <module>
                                                crunchy_main.main()
                                              File "C:\Users\colin\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_main.py", line 367, in main
                                                check_mode(args)
                                              File "C:\Users\colin\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_main.py", line 342, in check_mode
                                                crj.queue(args)
                                              File "C:\Users\colin\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_json.py", line 862, in queue
                                                'fanart')
                                              File "C:\Users\colin\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_json.py", line 779, in list_media_items
                                                queued=queued)
                                              File "C:\Users\colin\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_main.py", line 147, in add_item
                                                '&plot='       + urllib.quote_plus(info['plot']          +'%20')
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib.py", line 1292, in quote_plus
                                                if ' ' in s:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
```

**Comment by tamodolo** [comment]
I'll add an update: when I downgraded to version 1.7 the problem stoped and all was fine. Now repo version is 2.2 too and the error for that is the same as @evaryont (I think the first problem was caused by  malformed queue list, but this seems not to be the case).

the log:

> 09:50:53 T:4296  NOTICE: CR: makeAPIRequest: get JSON
> 09:50:53 T:4296  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/queue.0.json
> 09:50:53 T:4296  NOTICE: CR: makeAPIRequest: options = locale=ptBR&media_types=anime%7Cdrama&version=2313.8&session_id=ilkttxp5q2hfxevdvj650izca11adg0u&fields=media.episode_number%2Cmedia.name%2Cmedia.description%2Cmedia.media_type%2Cmedia.series_name%2Cmedia.available%2Cmedia.available_time%2Cmedia.free_available%2Cmedia.free_available_time%2Cmedia.duration%2Cmedia.url%2Cmedia.screenshot_image%2Cimage.fwide_url%2Cimage.fwidestar_url%2Cseries.landscape_image%2Cimage.full_url
> 09:50:57 T:4296  NOTICE: CR: A valid session was detected. Using existing session ID: ilkttxp5q2hfxevdvj650izca11adg0u
> 09:50:57 T:4296  NOTICE: CR: User is a premium anime|drama|manga member
> 09:50:57 T:4296  NOTICE: CR: Queue: queue type is 0
> 09:50:57 T:4296  NOTICE: CR: makeAPIRequest: get JSON
> 09:50:57 T:4296  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/queue.0.json
> 09:50:57 T:4296  NOTICE: CR: makeAPIRequest: options = locale=ptBR&media_types=anime%7Cdrama&version=2313.8&session_id=ilkttxp5q2hfxevdvj650izca11adg0u&fields=media.episode_number%2Cmedia.name%2Cmedia.description%2Cmedia.media_type%2Cmedia.series_name%2Cmedia.available%2Cmedia.available_time%2Cmedia.free_available%2Cmedia.free_available_time%2Cmedia.duration%2Cmedia.playhead%2Cmedia.url%2Cmedia.screenshot_image%2Cimage.fwide_url%2Cimage.fwidestar_url%2Cseries.landscape_image%2Cseries.series_id%2Cimage.full_url
> 09:50:59 T:4296  NOTICE: CR: Queue: request['error'] = False
> 09:50:59 T:4296  NOTICE: CR: Queue: has 76 series
> 09:50:59 T:4296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\tamod\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\default.py", line 38, in <module>
                                                crunchy_main.main()
                                              File "C:\Users\tamod\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_main.py", line 367, in main
                                                check_mode(args)
                                              File "C:\Users\tamod\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_main.py", line 342, in check_mode
                                                crj.queue(args)
                                              File "C:\Users\tamod\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_json.py", line 862, in queue
                                                'fanart')
                                              File "C:\Users\tamod\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_json.py", line 779, in list_media_items
                                                queued=queued)
                                              File "C:\Users\tamod\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_main.py", line 147, in add_item
                                                '&plot='       + urllib.quote_plus(info['plot']          +'%20')
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib.py", line 1292, in quote_plus
                                                if ' ' in s:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
> 09:50:59 T:6092   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.crunchyroll-takeout/?complete=True&count=0&duration=0&episode=0&fanart=C%3a%5cUsers%5ctamod%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.crunchyroll-takeout%5cfanart.jpg&filterx=None&icon=None&id=None&media_type=None&mode=queue&name=Queue&offset=0&playhead=0&plot=None%2520&season=1&series_id=None&url=None&year=0
> 09:50:59 T:6092   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll-takeout/?complete=True&count=0&duration=0&episode=0&fanart=C%3a%5cUsers%5ctamod%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.crunchyroll-takeout%5cfanart.jpg&filterx=None&icon=None&id=None&media_type=None&mode=queue&name=Queue&offset=0&playhead=0&plot=None%2520&season=1&series_id=None&url=None&year=0) failed

**Comment by tamodolo** [comment]
Sorry about the close/open. Cat's fault...

**Comment by Yoshiofthewire** [comment]
OK, so yeah I can replicate the issue,
IDK why it is doing this, because there is a default for that field.
I need to play with it.

**Comment by rpowellgit** [comment]
The problem is the series_id is getting set to None in crunchy_json.py's list_media_items().  The args.series_id is equal to None when this error happens.
        series_id = (media['series']['series_id']
                       if mode == "history"
                       else args.series_id)

I have a hard time wrapping my brain around ternary operators so i broke it down into a if/elif/else block below and it works.  I used the 'None' instead of None to make it urllib.quote() compatible.

diff --git a/resources/lib/crunchy_json.py b/resources/lib/crunchy_json.py
index be548de..9c49297 100644
--- a/resources/lib/crunchy_json.py
+++ b/resources/lib/crunchy_json.py
@@ -639,9 +639,12 @@ def list_media_items(args, request, series_name, season, mode, fanart):
     """
     for media in request:

-        series_id = (media['series']['series_id']
-                       if mode == "history"
-                       else args.series_id)
+        if mode == "history":
+            series_id = media['series']['series_id']
+        elif args.series_id:
+            series_id = args.series_id
+        else:
+            series_id = 'None'

         queued = (series_id in args.user_data['queue'])

**Comment by tamodolo** [comment]
I can confirm that this merge solved the issue.

There is a problem with the queue sort that isn't respecting order defined in the site but I'll open another issue since it's another problem.

Thank you very much!
