### ISSUE TITLE
Crunchyroll plugin fails to start

### ISSUE THREAD

**Issue by dpiorkowski** [Yoshiofthewire/CrunchyXBMC#47]
When I try to start the Crunchyroll plugin I get a "Crunchyroll Error" that says to check the log for more information. I'm using Kodi 16.1 on a first generation Amazon Fire TV. This plugin has worked 2 weeks ago without issue.

The error log is included below.

```
23:02:37 T:18446744072511695432  NOTICE: [PLUGIN] 'Crunchyroll: version 2.2.1' initialized!
23:02:39 T:18446744072511695432  NOTICE: CR: Valid auth token was detected. Restarting session.
23:02:39 T:18446744072511695432  NOTICE: CR: makeAPIRequest: get JSON
23:02:39 T:18446744072511695432  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/start_session.0.json
23:02:39 T:18446744072511695432  NOTICE: CR: makeAPIRequest: options = access_token=QWjz212GspMHH9h&version=2313.8&device_type=com.crunchyroll.iphone&locale=enUS&auth=CR%2FRkoseNt3nXEKfJBGHROgq2klJAA6d1%2FgGeY75eXy%2BCTYVWxBAyGGhcU9jjljHvBaZZGSEiuZCbpef1LYjyrbFHi6W34iYWII1q%2F9z2QOKuO9HShwHiDZwyTK%2FcFeLhYn0jfBaRvJg1ABTCTUuAA%3D%3D%3AS3Kt2vpWonVtUt1KkemErA%3D%3D&device_id=FFFFNGAv-KODI-aR5E-PwVC-FofeWK1qCLa8
23:02:39 T:18446744072511695432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'read'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/default.py", line 38, in <module>
                                                crunchy_main.main()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 359, in main
                                                if crj.load_pickle(args) is False:
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_json.py", line 188, in load_pickle
                                                current_datetime):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_json.py", line 316, in _restart_session
                                                args.user_data['auth_expires']    = dateutil.parser.parse(request['data']['expires'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/dateutil/parser.py", line 697, in parse
                                                return DEFAULTPARSER.parse(timestr, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/dateutil/parser.py", line 301, in parse
                                                res = self._parse(timestr, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/dateutil/parser.py", line 349, in _parse
                                                l = _timelex.split(timestr)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/dateutil/parser.py", line 143, in split
                                                return list(cls(s))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/dateutil/parser.py", line 137, in next
                                                token = self.get_token()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/dateutil/parser.py", line 68, in get_token
                                                nextchar = self.instream.read(1)
                                            AttributeError: 'NoneType' object has no attribute 'read'
                                            -->End of Python script error report<--
23:02:40 T:18446744072501558952   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.crunchyroll-takeout/
23:02:40 T:18446744072501558952   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll-takeout/) failed
23:08:47 T:18446744072523598768 WARNING: Attempt to use invalid handle -1
23:13:39 T:18446744072528855608 WARNING: Previous line repeats 8 times.
23:13:39 T:18446744072528855608 WARNING: JpegIO: Error 55: Not a JPEG file: starts with 0x%02x 0x%02x
23:13:55 T:18446744072525144344   ERROR: Unable to find plugin
23:13:55 T:18446744072501558952   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://
23:13:55 T:18446744072501558952   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
```

**Comment by igorcmoura** [comment]
I was having the same problem. The makeAPIRequest was returning a dictionary with None values:
```
{
	u'code': u'ok',
	u'data': {
		u'connectivity_type': u'unknown',
		u'country_code': u'BR',
		u'ops': [{
			u'params': {
				u'enableAppRating': True,
				u'allowInAppPurchases': True
			},
			u'op': u'feature_matrix'
		}],
		u'ip': <my ip>,
		u'expires': None,
		u'session_id': <session id>,
		u'version': u'2313.8',
		u'user': None,
		u'device_type': u'com.crunchyroll.iphone',
		u'debug': {
			u'connectivity_type': 0.00045919418334961,
			u'get_session': 0.0029590129852295,
			u'auth_an_client': 0.017494916915894,
			u'selector_fields': 9.5367431640625e-07,
			u'ops': 0.0034890174865723,
			u'locale': 0.001619815826416,
			u'parsed_url': 0.00032901763916016,
			u'translations': 0.061311006546021,
			u'init_app': 0.034060001373291,
			u'pre_view': 0.00033283233642578,
			u'require_once': 0.0001370906829834
		},
		u'auth': None,
		u'device_id': <device id>
	},
	u'error': False
}
```
I fixed it by forcing _start_session and now I'm unable to reproduce it :disappointed:
Anyway, a fast way to fix it is by deleting the crunchyPickle file located in crunchy plugin folder inside your addon data folder. It will delete your current session and start a new one.

**Comment by dpiorkowski** [comment]
That did it. Thanks.
