### ISSUE TITLE
Fails To Play Some Series

### ISSUE THREAD

**Issue by cwmke** [Yoshiofthewire/CrunchyXBMC#52]
I'm currently having an issue playing older shows such as Galaxy Express 999 or Linebarrels of Iron. I tried playing them on a fresh install as well and had the same errors. Thanks for any help.

~~~~~
00:35:24 T:4365060495104   DEBUG:   error
00:35:24 T:4365060495104   DEBUG:     False
00:35:24 T:4365060495104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('ultra',)
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.video.crunchyroll-takeout/default.py", line 38, in <module>
                                                crunchy_main.main()
                                              File "/home/user/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 367, in main
                                                check_mode(args)
                                              File "/home/user/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 348, in check_mode
                                                crj.start_playback(args)
                                              File "/home/user/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_json.py", line 1061, in start_playback
                                                if allurl[quality] is not None:
                                            KeyError: ('ultra',)
                                            -->End of Python script error report<--

00:35:24 T:4366383408640   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
00:35:24 T:4365060495104    INFO: Python script stopped
00:35:24 T:4365060495104   DEBUG: Thread LanguageInvoker 4365060495104 terminating
00:35:24 T:4366383408640   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
00:35:24 T:4366383408640   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.crunchyroll-takeout/?url=http%3A%2F%2Fwww.crunchyroll.com%2Fgalaxy-express-999%2Fepisode-39-kasumi-of-the-mist-capitol-512690&mode=videoplay&name=Episode+39+-+Kasumi+of+the+Mist+Capitol%5BCOLOR+FFbc3bfd%5D+%5BPlayed%5D+%5B%2FCOLOR%5D+%5BCOLOR+FF6fe335%5D28%25%5B%2FCOLOR%5D&id=512690&count=0&series_id=46828&filterx=None&offset=0&icon=http%3A%2F%2Fimg1.ak.crunchyroll.com%2Fi%2Fspire3-tmb%2F489b8c8fa41716bc615d3b41e51274e91230327429_fwide.jpg&complete=True&fanart=http%3A%2F%2Fimg1.ak.crunchyroll.com%2Fi%2Fspire3%2Fd23bbbebef0940de762429db6c0df4901266436625_full.jpg&season=1&media_type=None&year=2008-12-24&playhead=403&duration=1478&episode=39&plot=The+suitcase+with+Tetsuro+and+Maetel%27s+passes+is+stolen.+However%2C+the+thief+collapses+while+making+their+escape.+It+turns+out+the+people+on+this+planet+have+only+one+percent+of+a+normal+human%27s+physical+strength.+Even+a+gunshot+from+their+guns+barely+stings.+They+easily+get+their+suitcase+back%2C+but+the+passes+are+counterfeit%21%2520]
00:35:24 T:4366383408640   DEBUG: Playlist Player: no more playable items... aborting playback
00:35:24 T:4365060495104   DEBUG: Thread BackgroundLoader start, auto delete: false
00:35:24 T:4365060495104   DEBUG: Thread BackgroundLoader 4365060495104 terminating
00:35:28 T:4366383408640   DEBUG: Keyboard: scancode: 0x09, sym: 0x001b, unicode: 0x001b, modifier: 0x0
00:35:28 T:4366383408640   DEBUG: OnKey: escape (0xf01b) pressed, action is PreviousMenu
00:35:28 T:4366383408640   DEBUG: CGUIWindowManager::PreviousWindow: Deactivate
00:35:28 T:4366383408640   DEBUG: ------ Window Deinit (MyVideoNav.xml) ------
00:35:28 T:4366383408640   DEBUG: CGUIWindowManager::PreviousWindow: Activate new
00:35:28 T:4366383408640   DEBUG: ------ Window Init (Home.xml) ------
00:35:28 T:4365060495104   DEBUG: Thread LanguageInvoker start, auto delete: false
00:35:28 T:4365060495104    INFO: initializing python engine.
00:35:28 T:4365060495104   DEBUG: CPythonInvoker(26, /home/user/.kodi/addons/script.skinshortcuts/default.py): start processing
00:35:28 T:4364453209856   DEBUG: DoWork - trying to extract filestream details from video file plugin://plugin.video.crunchyroll-takeout/?url=http%3A%2F%2Fwww.crunchyroll.com%2Fgalaxy-express-999%2Fepisode-1-departure-ballad-512592&mode=videoplay&name=Episode+1+-+Departure+Ballad%5BCOLOR+FFbc3bfd%5D+%5BPlayed%5D+%5B%2FCOLOR%5D+%5BCOLOR+FF6fe335%5D95%25%5B%2FCOLOR%5D&id=512592&count=0&series_id=46828&filterx=None&offset=0&icon=http%3A%2F%2Fimg1.ak.crunchyroll.com%2Fi%2Fspire3-tmb%2Ffd4357967077b9deed0d90cd5848c35c1230303766_fwide.jpg&complete=True&fanart=http%3A%2F%2Fimg1.ak.crunchyroll.com%2Fi%2Fspire3%2Fd23bbbebef0940de762429db6c0df4901266436625_full.jpg&season=1&media_type=None&year=2009-01-09&playhead=1390&duration=1478&episode=1&plot=On+the+road+to+Megalopolis%2C+Tetsuro+is+encountered+by+Count+Mecha+and+watches+as+his+mother+is+killed.+Ironically%2C+he+is+rescued+by+a+woman+who+looks+remarkably+like+his+mother%2C+and+they+set+off+on+a+journey+on+the+Galaxy+Express+999.+He+begins+his+trek+towards+the+planet+where+he%27ll+be+able+to+receive+a+mechanical+body.%2520
~~~~~

**Comment by Neogrey** [comment]
The problem is, when you set a quality (under settings) which is not available for this stream. Set 360/480p for quality, and Galaxy Express 999 works for me.

I upload a fix in my repo, but needs some testing. Then I will pushing to this repo.

**Comment by cwmke** [comment]
Thanks! That does the trick.
