### ISSUE TITLE
Better remote playback URLs

### ISSUE THREAD

**Issue by xevz** [Yoshiofthewire/CrunchyXBMC#60]
Due to how check_mode() works, if I want to send a play video request to the Kodi API, I need to provide a lot of information that this plugin already looks up, such as title, season, icon and duration.

It looks something like this today:

    plugin://plugin.video.crunchyroll-takeout/movies?mode=videoplay&id=123&url=http://www.crunchyroll.com/show/episode-123&name=Video%20title&season=0&icon=None&duration=0

Instead of how it could look (see Twitch and Youtube addons):

    plugin://plugin.video.crunchyroll-takeout/video?id=123
    # or perhaps, if ID isn't enough
    plugin://plugin.video.crunchyroll-takeout/video?url=http://www.crunchyroll.com/show/episode-123

**Comment by davidkna** [comment]
`check_mode()` should be fine with stuff missing and on first look `start_playback()` should be, too.
Can you give me a code sample how I would use the Kodi API to navigate to a `plugin://` URL?
You should be fine either setting only the `id` or `url` right now.
Also I'm fairly sure the url should be `plugin://plugin.video.crunchyroll-takeout/?mode=videoplay&id=123` and not `plugin://plugin.video.crunchyroll-takeout/video?id=123`.

**Comment by xevz** [comment]
Using the URL plugin://plugin.video.crunchyroll-takeout/?mode=videoplay&id=730707
I get this exception:
```
15:59:07.485 T:139652489508608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'Args' object has no attribute 'name'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.crunchyroll-takeout/default.py", line 38, in <module>
                                                crunchy_main.main()
                                              File "/storage/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 367, in main
                                                check_mode(args)
                                              File "/storage/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 348, in check_mode
                                                crj.start_playback(args)
                                              File "/storage/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_json.py", line 1070, in start_playback
                                                item = xbmcgui.ListItem(args.name, path=url)
                                            AttributeError: 'Args' object has no attribute 'name'
                                            -->End of Python script error report<--
```

Here's the JSONRPC object:
```javascript
{:jsonrpc=>"2.0", :id=>1, :method=>"Player.Open", :params=>{:item=>{:file=>"plugin://plugin.video.crunchyroll-takeout/?mode=videoplay&id=730707"}}}
```

POST it to http://kodi/jsonrpc

You are correct that it works with just /?mode=... though.
This works:
```javascript
{:jsonrpc=>"2.0", :id=>1, :method=>"Player.Open", :params=>{:item=>{:file=>"plugin://plugin.video.crunchyroll-takeout/?mode=videoplay&id=730707&url=http://www.crunchyroll.com/my-hero-academia/episode-1-izuku-midoriya-origin-730707&name=My%20Hero%20Academia%20Episode%201%20-%20Izuku%20Midoriya:%20Origin&season=0&icon=None&duration=0"}}}
```

**Comment by davidkna** [comment]
Works for me. It looks like the issue is already solved and you only need to update to the version here on Github to get it working.

**Comment by AluminumGriffin** [comment]
plugin://plugin.video.crunchyroll-takeout/?id=543605
and
plugin://plugin.video.crunchyroll-takeout/?url=http://www.crunchyroll.com/bleach/episode-17-untitled-543605
works (note that id= or url= are the only commands passed)

The url-thing only works if mode= isn't set (I used this as a check to avoid messing up proper behaviour which always sets mode= )

Also, the url= thing works by just tossing everything before the last dash (-) and feeding the rest as id=
