### ISSUE TITLE
Crunchyroll Queue thowing error on access.

### ISSUE THREAD

**Issue by Haymish** [Yoshiofthewire/CrunchyXBMC#64]
When accessing the Queue in Crunchyroll Kodi it throws a error.
from Kodi.log

11:09:28.126 T:8668  NOTICE: CR: A valid session was detected. Using existing session ID: z51frcveopr03fpif20e1rqc4agzihra
11:09:28.126 T:8668  NOTICE: CR: User is a premium anime|drama|manga member
11:09:31.694 T:7980  NOTICE: CR: Queue: queue type is 0
11:09:31.694 T:7980  NOTICE: CR: makeAPIRequest: get JSON
11:09:31.695 T:7980  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/queue.0.json
11:09:31.695 T:7980  NOTICE: CR: makeAPIRequest: options = locale=enUS&media_types=anime%7Cdrama&version=2313.8&session_id=z51frcveopr03fpif20errqc4agzihra&fields=media.episode_number%2Cmedia.name%2Cmedia.description%2Cmedia.media_type%2Cmedia.series_name%2Cmedia.available%2Cmedia.available_time%2Cmedia.free_available%2Cmedia.free_available_time%2Cmedia.duration%2Cmedia.playhead%2Cmedia.url%2Cmedia.screenshot_image%2Cimage.fwide_url%2Cimage.fwidestar_url%2Cseries.landscape_image%2Cseries.series_id%2Cimage.full_url
11:09:32.299 T:7980  NOTICE: CR: Queue: request['error'] = False
11:09:32.299 T:7980  NOTICE: CR: Queue: has 29 series
11:09:32.301 T:7980   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('playhead',)
                                            Traceback (most recent call last):
                                              File "C:\Users\Tan\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\default.py", line 38, in <module>
                                                crunchy_main.main()
                                              File "C:\Users\Tan\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_main.py", line 367, in main
                                                check_mode(args)
                                              File "C:\Users\Tan\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_main.py", line 342, in check_mode
                                                crj.queue(args)
                                              File "C:\Users\Tan\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_json.py", line 865, in queue
                                                'fanart')
                                              File "C:\Users\Tan\AppData\Roaming\Kodi\addons\plugin.video.crunchyroll-takeout\resources\lib\crunchy_json.py", line 752, in list_media_items
                                                else str(media['playhead']))
                                            KeyError: ('playhead',)
                                            -->End of Python script error report<--
11:09:32.323 T:4976   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.crunchyroll-takeout/?complete=True&count=0&duration=0&episode=0&fanart=C%3a%5cUsers%5cTan%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.crunchyroll-takeout%5cfanart.jpg&filterx=None&icon=None&id=None&media_type=None&mode=queue&name=Queue&offset=0&playhead=0&plot=None%2520&season=1&series_id=None&url=None&year=0
11:09:32.323 T:4976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll-takeout/?complete=True&count=0&duration=0&episode=0&fanart=C%3a%5cUsers%5cTan%5cAppData%5cRoaming%5cKodi%5caddons%5cplugin.video.crunchyroll-takeout%5cfanart.jpg&filterx=None&icon=None&id=None&media_type=None&mode=queue&name=Queue&offset=0&playhead=0&plot=None%2520&season=1&series_id=None&url=None&year=0) failed

**Comment by Neogrey** [comment]
MrKrabat added a fix for this https://github.com/Yoshiofthewire/CrunchyXBMC/pull/57/commits/74451975b0210dc8484acf2a1dedfdc14524514f , now it is up to @Yoshiofthewire .
