### ISSUE TITLE
Error logging in from Kodi Krypton

### ISSUE THREAD

**Issue by JuanCAlpizar** [Yoshiofthewire/CrunchyXBMC#74]
Hello, I'm trying to use this plugin with Kodi 17.5. I cloned this repo, zipped it (I guess that's the proper way to install it since I found no further instructions on the README file) and installed from zip in Kodi. Everything went good, set my username and password (I'm a premium user) and tried to connect but I get this instead:

![image](https://user-images.githubusercontent.com/2028118/32119485-a4ce9e6e-bb12-11e7-95c7-c1b2dc6f4526.png)
When I proceed to check the `/home/jc/.kodi/temp/kodi.log` (whcih I assume is the log is refering to in the error dialog) I get the following as the latest part of the log:

    12:33:18.590 T:139745283798784  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
    12:33:20.269 T:139745812535360   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
    12:33:20.394 T:139745275406080  NOTICE: CR: Starting new session
    12:33:20.394 T:139745275406080  NOTICE: CR: makeAPIRequest: get JSON
    12:33:20.394 T:139745275406080  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/start_session.0.json
    12:33:20.394 T:139745275406080  NOTICE: CR: makeAPIRequest: options = locale=enUS&access_token=QWjz212GspMHH9h&version=2313.8&device_type=com.crunchyroll.iphone&device_id=FFFFrDJI-KODI-I4U7-HokW-0QjmSMF51nvJ
    12:33:20.926 T:139745275406080  NOTICE: CR: New session created! Session ID: ecigdr0ujjujbjucipl4i3sugzq1is4f
    12:33:20.926 T:139745275406080  NOTICE: CR: Login in the new session
    12:33:20.926 T:139745275406080  NOTICE: CR: makeAPIRequest: get JSON
    12:33:20.926 T:139745275406080  NOTICE: CR: makeAPIRequest: url = https://api.crunchyroll.com/login.0.json
    12:33:20.926 T:139745275406080  NOTICE: CR: makeAPIRequest: options = locale=enUS&password=********&account=********&version=2313.8&session_id=ecigdr0ujjujbjucipl4i3sugzq1is4f
    12:33:21.526 T:139745275406080   ERROR: CR: Error logging in new session. Error message: Your account has been locked. Please wait 2 hours or contact us.
    12:33:21.527 T:139745275406080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                Error Type: <type 'exceptions.KeyError'>
                                                Error Contents: ('mode',)
                                                Traceback (most recent call last):
                                                  File "/home/jc/.kodi/addons/plugin.video.crunchyroll-takeout/default.py", line 38, in <module>
                                                    crunchy_main.main()
                                                  File "/home/jc/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 440, in main
                                                    {'title': 'Session failed: Check login'})
                                                  File "/home/jc/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 177, in add_item
                                                    u = build_url(info)
                                                  File "/home/jc/.kodi/addons/plugin.video.crunchyroll-takeout/resources/lib/crunchy_main.py", line 147, in build_url
                                                    '&plot='       + urllib.quote_plus(info['plot']          +'%20')
                                                KeyError: ('mode',)
                                                -->End of Python script error report<--
    12:33:21.562 T:139745812535360   ERROR: GetDirectory - Error getting plugin://plugin.video.crunchyroll-takeout/
    12:33:21.563 T:139745812535360   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crunchyroll-takeout/) failed

What gets my attention is the message about failing logging in and locking account. If I try to enter the crunchyroll portal, my account works just fine. Any ideas why is it not working?

**Comment by JuanCAlpizar** [comment]
Additional info: if I perform the same POST request using Postman but using my clear username and password (which is obviously masked in the logs) directly copy and pasting them, I also get a forbidden result, so it's not the fact my username and password were typed wrong to begin with.

    {
        "error": true,
        "code": "forbidden",
        "message": "Your account has been locked. Please wait 2 hours or contact us."
    }

**Comment by AluminumGriffin** [comment]
I just put in a pull request to fix that (only the crunchy_main.py was changed)

However - the logs states that the call originates from generation of the "Session failed: Check login" message; which in most cases are wrong username/pass or that you changed it and didn't remove crunchyPickle (my pull request removes this automatically).

**Comment by JuanCAlpizar** [comment]
Hi, I'm just confirmed the last commit with this merge worked properly. I changed my password on CR, reinstalled, reset to defaults, uninstalled and reinstalled the lastest version and worked flawlessly, so I'm closing the issue now. Thanks for your support
